"""empty message

Revision ID: 21a4dfeeaa0b
Revises: 
Create Date: 2018-01-13 10:53:21.878311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a4dfeeaa0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('POI')
    op.drop_table('location_definition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.create_table('location_definition',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_icon', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_shape', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='location_definition_pkey')
    )
    op.create_table('POI',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"POI_id_seq"\'::regclass)'), nullable=False),
    sa.Column('datatourisme_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datatourisme_last_update', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_theme', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_lat_long', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('datatourisme_identifier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='POI_pkey')
    )
    # ### end Alembic commands ###
