"""empty message

Revision ID: 2301fa75febe
Revises: 21a4dfeeaa0b
Create Date: 2018-01-13 11:01:33.025390

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision = '2301fa75febe'
down_revision = '21a4dfeeaa0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attraction_name', sa.Text(), nullable=True),
    sa.Column('attraction_location', sa.Text(), nullable=True),
    sa.Column('attraction_type', sa.Text(), nullable=True),
    sa.Column('attraction_lat', sa.Float(), nullable=True),
    sa.Column('attraction_long', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('decription', sa.Text(), nullable=True),
    sa.Column('admin_type', sa.Text(), nullable=True),
    sa.Column('admin_level', sa.Integer(), nullable=True),
    sa.Column('centroid', Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('geometry', Geometry(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('locations')
    op.drop_table('attractions')
    # ### end Alembic commands ###
