"""empty message

Revision ID: 2deb7d8e9e93
Revises: 38218626bc89
Create Date: 2017-11-18 17:00:51.588426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2deb7d8e9e93'
down_revision = '38218626bc89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('location_lat', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('location_long', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('location_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'location_type')
    op.drop_column('locations', 'location_long')
    op.drop_column('locations', 'location_lat')
    # ### end Alembic commands ###
