"""empty message

Revision ID: 3802d1446956
Revises: 
Create Date: 2017-11-30 16:34:53.045779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3802d1446956'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attraction_name', sa.Text(), nullable=True),
    sa.Column('attraction_location', sa.Text(), nullable=True),
    sa.Column('attraction_type', sa.Text(), nullable=True),
    sa.Column('attraction_lat', sa.Float(), nullable=True),
    sa.Column('attraction_long', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_eu_region', sa.Text(), nullable=True),
    sa.Column('location_region_code', sa.Integer(), nullable=True),
    sa.Column('location_region_name', sa.Text(), nullable=True),
    sa.Column('location_region_capital', sa.Text(), nullable=True),
    sa.Column('location_department_no', sa.Integer(), nullable=True),
    sa.Column('location_department_name', sa.Text(), nullable=True),
    sa.Column('location_prefecture', sa.Text(), nullable=True),
    sa.Column('location_circumscription', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.Text(), nullable=True),
    sa.Column('location_postal_code', sa.Integer(), nullable=True),
    sa.Column('location_insee_code', sa.Integer(), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_long', sa.Float(), nullable=True),
    sa.Column('location_distance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    op.drop_table('attractions')
    # ### end Alembic commands ###
