"""empty message

Revision ID: 38218626bc89
Revises: 
Create Date: 2017-11-16 14:04:09.394239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38218626bc89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attraction_name', sa.Text(), nullable=True),
    sa.Column('attraction_location', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attractions')
    # ### end Alembic commands ###
