"""empty message

Revision ID: 54b52d0b00b0
Revises: 5d5ceea244ce
Create Date: 2017-11-19 10:44:29.062094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b52d0b00b0'
down_revision = '5d5ceea244ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attractions', sa.Column('attraction_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attractions', 'attraction_type')
    # ### end Alembic commands ###
