"""empty message

Revision ID: 5d5ceea244ce
Revises: 2deb7d8e9e93
Create Date: 2017-11-19 10:28:48.978777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5ceea244ce'
down_revision = '2deb7d8e9e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attractions', sa.Column('attraction_lat', sa.Float(), nullable=True))
    op.add_column('attractions', sa.Column('attraction_long', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attractions', 'attraction_long')
    op.drop_column('attractions', 'attraction_lat')
    # ### end Alembic commands ###
