"""empty message

Revision ID: 67eb2fcdfa16
Revises: ed883517e3f9
Create Date: 2017-12-08 15:39:15.605408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67eb2fcdfa16'
down_revision = 'ed883517e3f9'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_type', sa.Text(), nullable=True),
    sa.Column('location_icon', sa.Text(), nullable=True),
    sa.Column('location_color', sa.Text(), nullable=True),
    sa.Column('location_shape', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_definition')
    # ### end Alembic commands ###


def upgrade_gis_rhone_alpes():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_gis_rhone_alpes():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

