"""empty message

Revision ID: 798e10c4b747
Revises: a93007cf8f79
Create Date: 2018-02-06 15:39:24.122770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '798e10c4b747'
down_revision = 'a93007cf8f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_route',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('pace', sa.String(), nullable=True),
    sa.Column('itinerary_profile', sa.String(), nullable=True),
    sa.Column('amenity_profile', sa.String(), nullable=True),
    sa.Column('app_estimated_budget', sa.Numeric(precision=4, asdecimal=False), nullable=True),
    sa.Column('user_estimated_budget', sa.Numeric(precision=4, asdecimal=False), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('start_location', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('end_location', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('itinerary', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('route_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('user_route')
    # ### end Alembic commands ###
