"""empty message

Revision ID: 8ea17c54915a
Revises: b699ac1462df
Create Date: 2017-11-20 14:31:25.732351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea17c54915a'
down_revision = 'b699ac1462df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_eu_region', sa.Text(), nullable=True),
    sa.Column('location_region_code', sa.Integer(), nullable=True),
    sa.Column('location_region_name', sa.Text(), nullable=True),
    sa.Column('location_region_capital', sa.Text(), nullable=True),
    sa.Column('location_department_no', sa.Integer(), nullable=True),
    sa.Column('location_department_name', sa.Text(), nullable=True),
    sa.Column('location_prefecture', sa.Text(), nullable=True),
    sa.Column('location_circumscription', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.Text(), nullable=True),
    sa.Column('location_postal_code', sa.Integer(), nullable=True),
    sa.Column('location_insee_code', sa.Integer(), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_long', sa.Float(), nullable=True),
    sa.Column('location_distance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('locations2')
    op.drop_table('locations_fr_fr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations_fr_fr',
    sa.Column('location_eu_region', sa.TEXT(), nullable=True),
    sa.Column('location_region_code', sa.INTEGER(), nullable=True),
    sa.Column('location_region_name', sa.TEXT(), nullable=True),
    sa.Column('location_region_capital', sa.TEXT(), nullable=True),
    sa.Column('location_department_no', sa.INTEGER(), nullable=True),
    sa.Column('location_department_name', sa.TEXT(), nullable=True),
    sa.Column('location_prefecture', sa.TEXT(), nullable=True),
    sa.Column('location_circumscription', sa.INTEGER(), nullable=True),
    sa.Column('location_name', sa.TEXT(), nullable=True),
    sa.Column('location_postal_code', sa.INTEGER(), nullable=True),
    sa.Column('location_insee_code', sa.INTEGER(), nullable=True),
    sa.Column('location_lat', sa.REAL(), nullable=True),
    sa.Column('location_long', sa.REAL(), nullable=True),
    sa.Column('location_distance', sa.REAL(), nullable=True)
    )
    op.create_table('locations2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location_eu_region', sa.TEXT(), nullable=True),
    sa.Column('location_region_code', sa.INTEGER(), nullable=True),
    sa.Column('location_region_name', sa.TEXT(), nullable=True),
    sa.Column('location_region_capital', sa.TEXT(), nullable=True),
    sa.Column('location_department_no', sa.INTEGER(), nullable=True),
    sa.Column('location_department_name', sa.TEXT(), nullable=True),
    sa.Column('location_prefecture', sa.TEXT(), nullable=True),
    sa.Column('location_circumscription', sa.INTEGER(), nullable=True),
    sa.Column('location_name', sa.TEXT(), nullable=True),
    sa.Column('location_postal_code', sa.INTEGER(), nullable=True),
    sa.Column('location_insee_code', sa.INTEGER(), nullable=True),
    sa.Column('location_lat', sa.FLOAT(), nullable=True),
    sa.Column('location_long', sa.FLOAT(), nullable=True),
    sa.Column('location_distance', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('locations')
    # ### end Alembic commands ###
