"""empty message

Revision ID: a4d78b087ee9
Revises: 2301fa75febe
Create Date: 2018-01-13 15:51:47.002914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = 'a4d78b087ee9'
down_revision = '2301fa75febe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attractions', sa.Column('centroid', Geometry(geometry_type='POINT'), nullable=True))
    op.add_column('attractions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('attractions', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('attractions', sa.Column('osm_id', sa.Integer(), nullable=True))
    op.add_column('attractions', sa.Column('osm_type', sa.Text(), nullable=True))
    op.drop_column('attractions', 'attraction_location')
    op.drop_column('attractions', 'attraction_lat')
    op.drop_column('attractions', 'attraction_long')
    op.drop_column('attractions', 'attraction_name')
    op.add_column('locations', sa.Column('description', sa.Text(), nullable=True))
    op.drop_index('idx_locations_centroid', table_name='locations')
    op.drop_index('idx_locations_geometry', table_name='locations')
    op.drop_column('locations', 'decription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('decription', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('idx_locations_geometry', 'locations', ['geometry'], unique=False)
    op.create_index('idx_locations_centroid', 'locations', ['centroid'], unique=False)
    op.drop_column('locations', 'description')
    op.add_column('attractions', sa.Column('attraction_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('attractions', sa.Column('attraction_long', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('attractions', sa.Column('attraction_lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('attractions', sa.Column('attraction_location', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('attractions', 'osm_type')
    op.drop_column('attractions', 'osm_id')
    op.drop_column('attractions', 'name')
    op.drop_column('attractions', 'description')
    op.drop_column('attractions', 'centroid')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
