"""empty message

Revision ID: b6ae80877e31
Revises: f1f017a06340
Create Date: 2017-12-02 01:12:51.415377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ae80877e31'
down_revision = 'f1f017a06340'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_gis_rhone_alpes():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.add_column('rhone_alpes_line', sa.Column('id', sa.BigInteger(), nullable=False))
    op.drop_index('rhone_alpes_line_index', table_name='rhone_alpes_line')
    op.drop_index('rhone_alpes_line_pkey', table_name='rhone_alpes_line')
    op.add_column('rhone_alpes_point', sa.Column('id', sa.BigInteger(), nullable=False))
    op.add_column('rhone_alpes_point', sa.Column('tracktype', sa.Text(), nullable=True))
    op.add_column('rhone_alpes_point', sa.Column('way_area', sa.Float(), nullable=True))
    op.drop_index('rhone_alpes_point_index', table_name='rhone_alpes_point')
    op.drop_index('rhone_alpes_point_pkey', table_name='rhone_alpes_point')
    op.add_column('rhone_alpes_polygon', sa.Column('id', sa.BigInteger(), nullable=False))
    op.drop_index('rhone_alpes_polygon_index', table_name='rhone_alpes_polygon')
    op.drop_index('rhone_alpes_polygon_pkey', table_name='rhone_alpes_polygon')
    op.drop_index('rhone_alpes_rels_parts', table_name='rhone_alpes_rels')
    op.add_column('rhone_alpes_roads', sa.Column('id', sa.BigInteger(), nullable=False))
    op.drop_index('rhone_alpes_roads_index', table_name='rhone_alpes_roads')
    op.drop_index('rhone_alpes_roads_pkey', table_name='rhone_alpes_roads')
    op.drop_index('rhone_alpes_ways_nodes', table_name='rhone_alpes_ways')
    # ### end Alembic commands ###


def downgrade_gis_rhone_alpes():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('rhone_alpes_ways_nodes', 'rhone_alpes_ways', ['nodes'], unique=False)
    op.create_index('rhone_alpes_roads_pkey', 'rhone_alpes_roads', ['osm_id'], unique=False)
    op.create_index('rhone_alpes_roads_index', 'rhone_alpes_roads', ['way'], unique=False)
    op.drop_column('rhone_alpes_roads', 'id')
    op.create_index('rhone_alpes_rels_parts', 'rhone_alpes_rels', ['parts'], unique=False)
    op.create_index('rhone_alpes_polygon_pkey', 'rhone_alpes_polygon', ['osm_id'], unique=False)
    op.create_index('rhone_alpes_polygon_index', 'rhone_alpes_polygon', ['way'], unique=False)
    op.drop_column('rhone_alpes_polygon', 'id')
    op.create_index('rhone_alpes_point_pkey', 'rhone_alpes_point', ['osm_id'], unique=False)
    op.create_index('rhone_alpes_point_index', 'rhone_alpes_point', ['way'], unique=False)
    op.drop_column('rhone_alpes_point', 'way_area')
    op.drop_column('rhone_alpes_point', 'tracktype')
    op.drop_column('rhone_alpes_point', 'id')
    op.create_index('rhone_alpes_line_pkey', 'rhone_alpes_line', ['osm_id'], unique=False)
    op.create_index('rhone_alpes_line_index', 'rhone_alpes_line', ['way'], unique=False)
    op.drop_column('rhone_alpes_line', 'id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

