"""empty message

Revision ID: f1f017a06340
Revises: 6666a9e8aee7
Create Date: 2017-12-01 22:09:55.231162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f017a06340'
down_revision = '6666a9e8aee7'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_gis_rhone_alpes():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('rhone_alpes_line', sa.Column('harbour', sa.Text(), nullable=True))
    op.drop_index('idx_rhone_alpes_line_way', table_name='rhone_alpes_line')
    op.drop_column('rhone_alpes_line', 'harbor')
    op.add_column('rhone_alpes_point', sa.Column('harbour', sa.Text(), nullable=True))
    op.drop_index('idx_rhone_alpes_point_way', table_name='rhone_alpes_point')
    op.drop_column('rhone_alpes_point', 'harbor')
    op.add_column('rhone_alpes_polygon', sa.Column('harbour', sa.Text(), nullable=True))
    op.drop_index('idx_rhone_alpes_polygon_way', table_name='rhone_alpes_polygon')
    op.drop_column('rhone_alpes_polygon', 'harbor')
    op.add_column('rhone_alpes_roads', sa.Column('harbour', sa.Text(), nullable=True))
    op.drop_index('idx_rhone_alpes_roads_way', table_name='rhone_alpes_roads')
    op.drop_column('rhone_alpes_roads', 'harbor')
    # ### end Alembic commands ###


def downgrade_gis_rhone_alpes():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rhone_alpes_roads', sa.Column('harbor', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('idx_rhone_alpes_roads_way', 'rhone_alpes_roads', ['way'], unique=False)
    op.drop_column('rhone_alpes_roads', 'harbour')
    op.add_column('rhone_alpes_polygon', sa.Column('harbor', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('idx_rhone_alpes_polygon_way', 'rhone_alpes_polygon', ['way'], unique=False)
    op.drop_column('rhone_alpes_polygon', 'harbour')
    op.add_column('rhone_alpes_point', sa.Column('harbor', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('idx_rhone_alpes_point_way', 'rhone_alpes_point', ['way'], unique=False)
    op.drop_column('rhone_alpes_point', 'harbour')
    op.add_column('rhone_alpes_line', sa.Column('harbor', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('idx_rhone_alpes_line_way', 'rhone_alpes_line', ['way'], unique=False)
    op.drop_column('rhone_alpes_line', 'harbour')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###

