"""empty message

Revision ID: fc1fe80ba812
Revises: 760786c6a1f3
Create Date: 2017-12-08 15:41:29.075314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1fe80ba812'
down_revision = '760786c6a1f3'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_type', sa.Text(), nullable=True),
    sa.Column('location_icon', sa.Text(), nullable=True),
    sa.Column('location_color', sa.Text(), nullable=True),
    sa.Column('location_shape', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_definition')
    # ### end Alembic commands ###


def upgrade_gis_rhone_alpes():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_gis_rhone_alpes():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

