"""empty message

Revision ID: fd64447b8bd4
Revises: 1bf54f8ab81b
Create Date: 2017-12-10 15:55:11.433885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd64447b8bd4'
down_revision = '1bf54f8ab81b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=80), nullable=False),
    sa.Column('route_JSON', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_route')
    # ### end Alembic commands ###


def upgrade_gis_rhone_alpes():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_gis_rhone_alpes():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

